steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '[$PROJECT_ID]-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '.']
    id: Building the container image

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '[$PROJECT_ID]-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}']
    id: Pushing the image to Artifact Registry

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', '{$PROJECT_ID}-docker.pkg.dev/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '--region', 'asia-south2', '--platform', 'managed', "--allow-unauthenticated"]
options:
  logging: CLOUD_LOGGING_ONLY
